CREATE TYPE [dbo].[AspNetUserstype] AS TABLE (
    [Id]                                            UNIQUEIDENTIFIER NOT NULL,
    [Email]                                         NVARCHAR (256)   NULL,
    [EmailConfirmed]                                BIT              NOT NULL,
    [PasswordHash]                                  NVARCHAR (MAX)   NULL,
    [SecurityStamp]                                 NVARCHAR (MAX)   NULL,
    [PhoneNumber]                                   NVARCHAR (MAX)   NULL,
    [PhoneNumberConfirmed]                          BIT              NOT NULL,
    [TwoFactorEnabled]                              BIT              NOT NULL,
    [LockoutEndDateUtc]                             DATETIME2 (7)    NULL,
    [LockoutEnabled]                                BIT              NOT NULL,
    [IsLockedOut]                                   BIT              NOT NULL,
    [AccessFailedCount]                             INT              NOT NULL,
    [UserName]                                      NVARCHAR (256)   NOT NULL,
    [IsActive]                                      BIT              NOT NULL,
    [IsInternalUser]                                BIT              NOT NULL,
    [UserPreferencesJson]                           NVARCHAR (MAX)   NULL,
    [FirstName]                                     NVARCHAR (100)   NULL,
    [MiddleName]                                    NVARCHAR (100)   NULL,
    [LastName]                                      NVARCHAR (100)   NULL,
    [Salutation]                                    NVARCHAR (100)   NULL,
    [DrNpi]                                         NVARCHAR (100)   NULL,
    [IsSpecialtyEndodontics]                        BIT              NOT NULL,
    [IsSpecialtyOrthodonticsDentofacialOrthopedics] BIT              NOT NULL,
    [IsSpecialtyOralMaxillofacialPathology]         BIT              NOT NULL,
    [IsSpecialtyPediatricDentistry]                 BIT              NOT NULL,
    [IsSpecialtyPeriodontics]                       BIT              NOT NULL,
    [IsSpecialtyProsthodontics]                     BIT              NOT NULL,
    [IsSpecialtyDentalPublicHealth]                 BIT              NOT NULL,
    [IsSpecialtyOralMaxillofacialRadiology]         BIT              NOT NULL,
    [IsSpecialtyOralMaxillofacialSurgery]           BIT              NOT NULL,
    [ChangeUtc]                                     DATETIME2 (7)    NOT NULL,
    [ChangeUserGuid]                                UNIQUEIDENTIFIER NOT NULL,
    [ChangeProgramName]                             NVARCHAR (100)   NOT NULL,
    [CreateUtc]                                     DATETIME2 (7)    NOT NULL,
    [CreateUserGuid]                                UNIQUEIDENTIFIER NOT NULL,
    [CreateProgramName]                             NVARCHAR (100)   NOT NULL,
    [IsAdUser]                                      BIT              NULL,
    [LastLoginUtc]                                  DATETIME2 (7)    NULL,
    [IsMarginMarkingCertified]                      BIT              NULL,
    [BillingAccountGuid]                            UNIQUEIDENTIFIER NULL,
    [MarginMarkingCertificationDateTime]            DATETIME         NULL,
    [MarginMarkingCertificationStatus]              INT              NULL,
    [DdsUserPreferencesJson]                        NVARCHAR (MAX)   NULL,
    [WelcomeLastSentUtc]                            DATETIME2 (7)    NULL,
    [ChangePasswordReminderUtc]                     DATETIME2 (7)    NULL,
    [LastFirstName]                                 VARCHAR (1000)   NULL,
    [FirstLastName]                                 VARCHAR (1000)   NULL,
    [EmailMeDraftedOrder]                           BIT              NULL,
    [EmailMeSubmittedOrder]                         BIT              NULL,
    [EmailMeOnHoldOrder]                            BIT              NULL,
    [EmailMeCanceledOrder]                          BIT              NULL,
    [EmailMeReviewReadyOrder]                       BIT              NULL,
    [EmailMeRefinementReadyOrder]                   BIT              NULL,
    [EmailMeNewMessages]                            BIT              NULL,
    [EmailMeAwaitingImpressions]                    BIT              NULL,
    [EmailMeRejectedOrder]                          BIT              NULL,
    [AnnouncementLastViewedUtc]                     DATETIME         NULL);

