CREATE TYPE [dbo].[StoredFiletype] AS TABLE (
    [StoredFileGuid]            UNIQUEIDENTIFIER NOT NULL,
    [PatientGuid]               UNIQUEIDENTIFIER NULL,
    [FileLocationUri]           NVARCHAR (1000)  NULL,
    [FriendlyFileName]          NVARCHAR (1000)  NULL,
    [CheckSumHash]              VARBINARY (60)   NULL,
    [FileSizeInBytes]           BIGINT           NULL,
    [FileTypeValue]             INT              NOT NULL,
    [ScanTypeValue]             INT              NULL,
    [PatientRecordTypeValue]    INT              NULL,
    [TinyThumbnail]             VARBINARY (MAX)  NULL,
    [ThumbnailFileLocationUri]  NVARCHAR (1000)  NULL,
    [IsActive]                  BIT              NOT NULL,
    [ChangeUtc]                 DATETIME2 (7)    NOT NULL,
    [ChangeUserGuid]            UNIQUEIDENTIFIER NOT NULL,
    [ChangeProgramName]         NVARCHAR (100)   NOT NULL,
    [CreateUtc]                 DATETIME2 (7)    NOT NULL,
    [CreateUserGuid]            UNIQUEIDENTIFIER NOT NULL,
    [CreateProgramName]         NVARCHAR (100)   NOT NULL,
    [CompressionAlgorithmValue] INT              NULL,
    [IsFileCompressed]          BIT              NULL,
    [ScanStageValue]            INT              NULL,
    [LccStoredFileId]           UNIQUEIDENTIFIER NULL,
    [QuickScanFileGuid]         UNIQUEIDENTIFIER NULL,
    [ScannerTypeValue]          INT              NULL,
    [FileGroupGuid]             UNIQUEIDENTIFIER NULL,
    [FileSourceValue]           INT              NULL);

