CREATE TABLE [etl].[DimDate] (
    [DateKey]                   INT          NOT NULL,
    [Date]                      DATE         NULL,
    [DayOfMonth]                VARCHAR (2)  NULL,
    [DaySuffix]                 VARCHAR (4)  NULL,
    [DayName]                   VARCHAR (9)  NULL,
    [DayShortName]              VARCHAR (3)  NULL,
    [DayOfWeek]                 CHAR (1)     NULL,
    [IsWeekday]                 BIT          NULL,
    [WeekStartDate]             DATE         NULL,
    [WeekStartDateShortName]    VARCHAR (50) NULL,
    [WeekStartDateSortKey]      INT          NULL,
    [WeekOfMonth]               VARCHAR (1)  NULL,
    [WeekOfQuarter]             VARCHAR (2)  NULL,
    [WeekOfYear]                VARCHAR (2)  NULL,
    [Month]                     VARCHAR (2)  NULL,
    [MonthName]                 VARCHAR (9)  NULL,
    [MonthShortName]            VARCHAR (3)  NULL,
    [MonthStartDate]            DATE         NULL,
    [MonthStartDateShortName]   VARCHAR (50) NULL,
    [MonthStartDateSortKey]     INT          NULL,
    [MonthEndDate]              DATE         NULL,
    [MonthEndDateShortName]     VARCHAR (50) NULL,
    [MonthEndDateSortKey]       INT          NULL,
    [MonthOfQuarter]            VARCHAR (2)  NULL,
    [Quarter]                   CHAR (1)     NULL,
    [QuarterName]               VARCHAR (9)  NULL,
    [QuarterStartDate]          DATE         NULL,
    [QuarterStartDateShortName] VARCHAR (50) NULL,
    [QuarterStartDateSortKey]   INT          NULL,
    [QuarterEndDate]            DATE         NULL,
    [QuarterEndDateShortName]   VARCHAR (50) NULL,
    [QuarterEndDateSortKey]     INT          NULL,
    [Year]                      CHAR (4)     NULL,
    [MonthYearName]             CHAR (10)    NULL,
    [YYYY-WW]                   CHAR (7)     NULL,
    [YearStartDate]             DATE         NULL,
    [YearStartDateShortName]    VARCHAR (50) NULL,
    [YearStartDateSortKey]      INT          NULL,
    [YearEndDate]               DATE         NULL,
    [YearEndDateShortName]      VARCHAR (50) NULL,
    [YearEndDateSortKey]        INT          NULL,
    [IsHolidayUSA]              BIT          NULL,
    [HolidayUSA]                VARCHAR (50) NULL,
    [IsWorkingdayUSA]           BIT          NULL,
    PRIMARY KEY CLUSTERED ([DateKey] ASC)
);

