CREATE TABLE [qa].[DimDate] (
    [DateKey]           INT           NOT NULL,
    [Date]              DATETIME2 (7) NOT NULL,
    [DayOfMonth]        INT           NOT NULL,
    [DaySuffix]         NVARCHAR (50) NOT NULL,
    [DayName]           NVARCHAR (50) NOT NULL,
    [DayShortName]      NVARCHAR (50) NOT NULL,
    [DayOfWeek]         INT           NOT NULL,
    [WeekOfMonth]       INT           NOT NULL,
    [WeekOfQuarter]     INT           NOT NULL,
    [WeekOfYear]        INT           NOT NULL,
    [Month]             INT           NOT NULL,
    [MonthName]         NVARCHAR (50) NOT NULL,
    [MonthShortName]    NVARCHAR (50) NOT NULL,
    [MonthOfQuarter]    INT           NOT NULL,
    [Quarter]           INT           NOT NULL,
    [QuarterName]       NVARCHAR (50) NOT NULL,
    [Year]              INT           NOT NULL,
    [MonthYear]         DATETIME2 (7) NOT NULL,
    [MMYYYY]            INT           NOT NULL,
    [YYYY_WW]           NVARCHAR (50) NOT NULL,
    [MMM_DD]            NVARCHAR (50) NOT NULL,
    [FirstDayOfMonth]   DATETIME2 (7) NOT NULL,
    [LastDayOfMonth]    DATETIME2 (7) NOT NULL,
    [FirstDayOfQuarter] DATETIME2 (7) NOT NULL,
    [LastDayOfQuarter]  DATETIME2 (7) NOT NULL,
    [FirstDayOfYear]    DATETIME2 (7) NOT NULL,
    [LastDayOfYear]     DATETIME2 (7) NOT NULL,
    [IsHolidayUSA]      BIT           NOT NULL,
    [IsWeekday]         BIT           NOT NULL,
    [HolidayUSA]        NVARCHAR (50) NOT NULL,
    [IsWorkingdayUSA]   BIT           NOT NULL
);

