CREATE TABLE [qa].[FactDoctorDetailHistory] (
    [SnapshotDateKey]                   INT           NOT NULL,
    [SalesRepKey]                       NVARCHAR (50) NOT NULL,
    [BillingAccountKey]                 INT           NOT NULL,
    [DoctorKey]                         INT           NOT NULL,
    [FirstInviteDate]                   DATETIME2 (7) NOT NULL,
    [LastInviteDate]                    NVARCHAR (50) NOT NULL,
    [FirstLoginDate]                    NVARCHAR (50) NOT NULL,
    [LastLoginDate]                     NVARCHAR (50) NOT NULL,
    [FirstInviteDateKey]                INT           NOT NULL,
    [LastInviteDateKey]                 NVARCHAR (50) NOT NULL,
    [FirstLoginDateKey]                 NVARCHAR (50) NOT NULL,
    [LastLoginDateKey]                  NVARCHAR (50) NOT NULL,
    [FirstPrescriptionSubmittedDate]    NVARCHAR (50) NOT NULL,
    [LastPrescriptionSubmittedDate]     NVARCHAR (50) NOT NULL,
    [FirstRefinementSubmittedDate]      NVARCHAR (50) NOT NULL,
    [LastRefinementSubmittedDate]       NVARCHAR (50) NOT NULL,
    [FirstSubmittedDate]                NVARCHAR (50) NOT NULL,
    [LastSubmittedDate]                 NVARCHAR (50) NOT NULL,
    [FirstPrescriptionSubmittedDateKey] NVARCHAR (50) NOT NULL,
    [LastPrescriptionSubmittedDateKey]  NVARCHAR (50) NOT NULL,
    [FirstRefinementSubmittedDateKey]   NVARCHAR (50) NOT NULL,
    [LastRefinementSubmittedDateKey]    NVARCHAR (50) NOT NULL,
    [FirstSubmittedDateKey]             NVARCHAR (50) NOT NULL,
    [LastSubmittedDateKey]              NVARCHAR (50) NOT NULL,
    [IsDoctorActiveLastWeek]            INT           NOT NULL,
    [OrdersApproved]                    NVARCHAR (50) NOT NULL,
    [NumberOfSetupsPerCase]             NVARCHAR (50) NOT NULL,
    [NumberOfSetupsPerOrder]            NVARCHAR (50) NOT NULL,
    [AvgSetupReviewTimeInDays]          NVARCHAR (50) NOT NULL,
    [AvgOrderApprovalTimeInDays]        NVARCHAR (50) NOT NULL
);

