CREATE TABLE [qa].[OrthoRefinement] (
    [SalesOrderGuid]            VARCHAR (256)  NULL,
    [DentalStatusHistoryGuid]   VARCHAR (256)  NULL,
    [VersionNumber]             INT            NULL,
    [FinalSetupValue]           INT            NULL,
    [FinalSetupText]            NVARCHAR (MAX) NULL,
    [ExistingAttachmentValue]   INT            NULL,
    [ExistingAttachmentCsv]     NVARCHAR (200) NULL,
    [NewAttachmentValue]        INT            NULL,
    [NewAttachmentCsv]          NVARCHAR (200) NULL,
    [NewAttachmentText]         NVARCHAR (MAX) NULL,
    [IprValue]                  INT            NULL,
    [IprCsv]                    NVARCHAR (200) NULL,
    [AdditionalIprValue]        INT            NULL,
    [AdditionalIprCsv]          NVARCHAR (200) NULL,
    [SpacesValue]               INT            NULL,
    [SpacesCsv]                 NVARCHAR (200) NULL,
    [AdditionalInstructionText] NVARCHAR (MAX) NULL,
    [IsActive]                  BIT            NULL,
    [ChangeUtc]                 DATETIME2 (7)  NULL,
    [ChangeUserGuid]            VARCHAR (256)  NULL,
    [ChangeProgramName]         NVARCHAR (100) NULL,
    [CreateUtc]                 DATETIME2 (7)  NULL,
    [CreateUserGuid]            VARCHAR (256)  NULL,
    [CreateProgramName]         NVARCHAR (100) NULL,
    [IsOverCorrection]          BIT            NULL,
    [ProcessedDateTime]         DATETIME       NOT NULL
);

