CREATE EXTERNAL TABLE [dbo].[OrthoPrescription] (
    [SalesOrderGuid] UNIQUEIDENTIFIER NULL,
    [DentalStatusHistoryGuid] UNIQUEIDENTIFIER NULL,
    [WearScheduleInMinutes] INT NULL,
    [LowerArchTreatmentBitwise] INT NULL,
    [UpperArchTreatmentBitwise] INT NULL,
    [RetainerQuantity] INT NULL,
    [OverbiteValue] INT NULL,
    [OverbiteOpenValue] INT NULL,
    [OverbiteDeepValue] INT NULL,
    [OverbiteArchValue] INT NULL,
    [OverbiteText] NVARCHAR (MAX) NULL,
    [OverjetValue] INT NULL,
    [OverjetText] NVARCHAR (MAX) NULL,
    [ApMaintainSideValue] INT NULL,
    [ApCanineOnlySideValue] INT NULL,
    [ApCaninieMolarSideValue] INT NULL,
    [ApCaninieMolarText] NVARCHAR (MAX) NULL,
    [ClassCorrectionSideValue] INT NULL,
    [ClassCorrectionValue] INT NULL,
    [IsClassCorrectionPosteriorIpr] BIT NULL,
    [IsClassCorrectionSimulation] BIT NULL,
    [IsClassCorrectionDistalization] BIT NULL,
    [ClassCorrectionMovementText] NVARCHAR (MAX) NULL,
    [ClassCorrectionExtractionsText] NVARCHAR (MAX) NULL,
    [AnteriorCrossbiteCorrectionValue] INT NULL,
    [PosteriorCrossbiteCorrectionValue] INT NULL,
    [CrossbiteText] NVARCHAR (MAX) NULL,
    [MidlineValue] INT NULL,
    [IsImproveMidlineUpperRight] BIT NULL,
    [IsImproveMidlineUpperLeft] BIT NULL,
    [IsImproveMidlineLowerRight] BIT NULL,
    [IsImproveMidlineLowerLeft] BIT NULL,
    [MidlineText] NVARCHAR (MAX) NULL,
    [AnteriorLevelingValue] INT NULL,
    [AnteriorLevelingText] NVARCHAR (MAX) NULL,
    [SpacesValue] INT NULL,
    [SpacesCsv] NVARCHAR (200) NULL,
    [SpacesText] NVARCHAR (MAX) NULL,
    [UpperExpandCrowdingValue] INT NULL,
    [UpperProclineCrowdingValue] INT NULL,
    [UpperIprAnteriorCrowdingValue] INT NULL,
    [UpperIprPosteriorRightCrowdingValue] INT NULL,
    [UpperIprPosteriorLeftCrowdingValue] INT NULL,
    [LowerExpandCrowdingValue] INT NULL,
    [LowerProclineCrowdingValue] INT NULL,
    [LowerIprAnteriorCrowdingValue] INT NULL,
    [LowerIprPosteriorRightCrowdingValue] INT NULL,
    [LowerIprPosteriorLeftCrowdingValue] INT NULL,
    [CrowdingText] NVARCHAR (MAX) NULL,
    [ArchFormValue] INT NULL,
    [ArchFormText] NVARCHAR (MAX) NULL,
    [AttachmentsValue] INT NULL,
    [AttachmentsCsv] NVARCHAR (200) NULL,
    [AttachmentsText] NVARCHAR (MAX) NULL,
    [PrescriptionText] NVARCHAR (MAX) NULL,
    [StagesPerShipmentQuantity] INT NULL,
    [IsActive] BIT NULL,
    [ChangeUtc] DATETIME2 (7) NULL,
    [ChangeUserGuid] UNIQUEIDENTIFIER NULL,
    [ChangeProgramName] NVARCHAR (100) NULL,
    [CreateUtc] DATETIME2 (7) NULL,
    [CreateUserGuid] UNIQUEIDENTIFIER NULL,
    [CreateProgramName] NVARCHAR (100) NULL,
    [SubmitterUserGuid] UNIQUEIDENTIFIER NULL,
    [SubmitterFullName] NVARCHAR (255) NULL,
    [VersionNumber] INT NULL,
    [RightApRelationshipValue] INT NULL,
    [LeftApRelationshipValue] INT NULL,
    [TrimLineLowerValue] INT NULL,
    [TrimLineUpperValue] INT NULL,
    [IncludeCutsForElastics] BIT NULL,
    [ElasticsStartStage] INT NULL,
    [PreferredCutsValue] INT NULL,
    [IsOverCorrection] BIT NULL,
    [TeethBondCsv] NVARCHAR (200) NULL,
    [BracketHooksCsv] NVARCHAR (200) NULL,
    [UpperBracketTypeValue] INT NULL,
    [LowerBracketTypeValue] INT NULL,
    [SlotSizeValue] INT NULL,
    [IbtArchFormValue] INT NULL,
    [UpperArchRadiusValue] INT NULL,
    [LowerArchRadiusValue] INT NULL,
    [PreferredTrayTypeValue] INT NULL,
    [IbtAdditionalInstructionText] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [RemoteDbProd],
    SCHEMA_NAME = N'dbo',
    OBJECT_NAME = N'OrthoPrescription'
    );

