CREATE EXTERNAL TABLE [dbo].[SalesOrder] (
    [SalesOrderGuid] UNIQUEIDENTIFIER NULL,
    [RootSalesOrderGuid] UNIQUEIDENTIFIER NULL,
    [ParentSalesOrderGuid] UNIQUEIDENTIFIER NULL,
    [DentalCaseGuid] UNIQUEIDENTIFIER NULL,
    [SalesOrderDate] DATE NULL,
    [SalesOrderId] NVARCHAR (30) NULL,
    [OrderStateUtc] DATETIME2 (7) NULL,
    [OrderStateValue] INT NULL,
    [OrderTypeValue] INT NULL,
    [SubmittedUtc] DATETIME2 (7) NULL,
    [IsActive] BIT NULL,
    [IsOrderModifiedAfterSubmission] BIT NULL,
    [ChangeUtc] DATETIME2 (7) NULL,
    [ChangeUserGuid] UNIQUEIDENTIFIER NULL,
    [ChangeProgramName] NVARCHAR (100) NULL,
    [CreateUtc] DATETIME2 (7) NULL,
    [CreateUserGuid] UNIQUEIDENTIFIER NULL,
    [CreateProgramName] NVARCHAR (100) NULL,
    [EstimatedDeliveryDate] DATE NULL,
    [ManufacturingWorkOrderId] NVARCHAR (20) NULL,
    [ReasonForCancellationText] NVARCHAR (MAX) NULL,
    [ReorderReasonValue] INT NULL,
    [SalesOrderName] NVARCHAR (100) NULL,
    [BillingAccountGuid] UNIQUEIDENTIFIER NULL,
    [AdditionalInformationText] NVARCHAR (MAX) NULL,
    [RefinementLastCompletedIterationNumber] INT NULL,
    [PatientGuid] UNIQUEIDENTIFIER NULL,
    [ProductLegalAgreementGuidList] NVARCHAR (100) NULL,
    [ImpressionDate] DATE NULL,
    [MaterialTypeValue] INT NULL,
    [SubmitterUserGuid] UNIQUEIDENTIFIER NULL,
    [SubmitterFullName] NVARCHAR (255) NULL,
    [QcDataCleanupText] NVARCHAR (MAX) NULL,
    [QcDifficultyValue] INT NULL,
    [IsExpedited] BIT NULL,
    [AssignedToUserGuid] UNIQUEIDENTIFIER NULL,
    [CarrierValue] INT NULL,
    [CarrierTrackingId] NVARCHAR (50) NULL,
    [InfoVersion] INT NULL
)
    WITH (
    DATA_SOURCE = [RemoteDbProd],
    SCHEMA_NAME = N'dbo',
    OBJECT_NAME = N'SalesOrder'
    );

