CREATE EXTERNAL TABLE [dbo].[vDigitalModel] (
    [DigitalModelGuid] UNIQUEIDENTIFIER NULL,
    [IsActive] BIT NULL,
    [IsModelOnHold] BIT NULL,
    [SalesOrderId] NVARCHAR (20) NULL,
    [SalesOrderGuid] UNIQUEIDENTIFIER NULL,
    [IterationNumber] INT NULL,
    [ModelTypeDescription] NVARCHAR (100) NULL,
    [ModelTypeValue] INT NULL,
    [ModelStateDescription] NVARCHAR (100) NULL,
    [ModelStateValue] INT NULL,
    [ModelStateUtc] DATETIME2 (7) NULL,
    [MaxIterationNumber] INT NULL,
    [DataCleanupUtc] DATETIME NULL,
    [DataCleanupByEmailName] NVARCHAR (256) NULL,
    [DataCleanupCompleteUtc] DATETIME NULL,
    [DataCleanupCompleteByEmailName] NVARCHAR (256) NULL,
    [BiteAlignmentStartUtc] DATETIME NULL,
    [BiteAlignmentStartByEmailName] NVARCHAR (256) NULL,
    [BiteAlignmentUtc] DATETIME NULL,
    [BiteAlignmentByEmailName] NVARCHAR (256) NULL,
    [BiteAlignmentCompleteUtc] DATETIME NULL,
    [BiteAlignmentCompleteByEmailName] NVARCHAR (256) NULL,
    [AutoSegmentationCompleteUtc] DATETIME NULL,
    [AutoSegmentationCompleteByEmailName] NVARCHAR (256) NULL,
    [SegmentationStartUtc] DATETIME NULL,
    [SegmentationStartByEmailName] NVARCHAR (256) NULL,
    [SegmentationCompleteUtc] DATETIME NULL,
    [SegmentationCompleteByEmailName] NVARCHAR (256) NULL,
    [LandmarkingUtc] DATETIME NULL,
    [LandmarkingByEmailName] NVARCHAR (256) NULL,
    [LandmarkingCompleteUtc] DATETIME NULL,
    [LandmarkingCompleteByEmailName] NVARCHAR (256) NULL,
    [DigitalSetupUtc] DATETIME NULL,
    [DigitalSetupByEmailName] NVARCHAR (256) NULL,
    [DigitalSetupCompleteUtc] DATETIME NULL,
    [DigitalSetupCompleteByEmailName] NVARCHAR (256) NULL,
    [StagingSetupUtc] DATETIME NULL,
    [StagingSetupByEmailName] NVARCHAR (256) NULL,
    [StagingSetupCompleteUtc] DATETIME NULL,
    [StagingSetupCompleteByEmailName] NVARCHAR (256) NULL,
    [StagingSetupQaCompleteUtc] DATETIME NULL,
    [StagingSetupQaCompleteByEmailName] NVARCHAR (256) NULL,
    [SetupReviewUtc] DATETIME NULL,
    [SetupReviewByEmailName] NVARCHAR (256) NULL,
    [SetupReviewDoctorUtc] DATETIME NULL,
    [SetupReviewDoctorByEmailName] NVARCHAR (256) NULL,
    [FixtureCompleteUtc] DATETIME NULL,
    [FixtureCompleteByEmailName] NVARCHAR (256) NULL,
    [ManufacturingDesignUtc] DATETIME NULL,
    [ManufacturingDesignByEmailName] NVARCHAR (256) NULL,
    [ManufacturingDesignCompleteUtc] DATETIME NULL,
    [ManufacturingDesignCompleteByEmailName] NVARCHAR (256) NULL,
    [RollbackCount] INT NULL,
    [ReworkCount] INT NULL,
    [TotalWts] INT NULL,
    [ModelStateWts] INT NULL,
    [BiteAlignmentWts] INT NULL,
    [BiteAlignmentTimesCompleted] INT NULL,
    [SegmentationWts] INT NULL,
    [SegmentationTimesCompleted] INT NULL,
    [LandmarkingWts] INT NULL,
    [LandmarkingTimesCompleted] INT NULL,
    [RefinementSetupWts] INT NULL,
    [RefinementSetupTimesCompleted] INT NULL,
    [DigitalSetupWts] INT NULL,
    [DigitalSetupTimesCompleted] INT NULL,
    [StagingSetupWts] INT NULL,
    [StagingSetupTimesCompleted] INT NULL,
    [DigitalSetupQaWts] INT NULL,
    [DigitalSetupQaTimesCompleted] INT NULL,
    [ManufacturingDesignWts] INT NULL,
    [ManufacturingDesignTimesCompleted] INT NULL
)
    WITH (
    DATA_SOURCE = [RemoteDbProdDW],
    SCHEMA_NAME = N'dbo',
    OBJECT_NAME = N'vDigitalModel'
    );

